apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: simple-app
          image: hashicorp/http-echo:0.2.3  # Image siap pakai
          args:
            - "-text=Hello from ArgoCD!"
          ports:
            - containerPort: 5678
